version: "3.9"
services:
  web:
    build:
      context: ./
      dockerfile: Dockerfile
    image: timoshenko/prometheus_exporter:latest
    ports:
      - "2113:2113"
    networks:
      - bridge
    volumes:
      - .:/app
    env_file:
      - .env
  prometheus:
    image: prom/prometheus:v2.35.0
    ports:
      - 9000:9090
    volumes:
      - ./prometheus:/etc/prometheus
      - prometheus-data:/prometheus
    command: --web.enable-lifecycle  --config.file=/etc/prometheus/prometheus.yml
    networks:
      - bridge
volumes:
  prometheus-data:
networks:
  bridge:
    driver: bridge